name: Build and deploy to Nuget

on:
  push:
    branches:
      - dev
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

  nuget:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      - name: Create and push NuGet package
        run: |
          dotnet pack TinyTypes.sln -c Release -o nuget -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          dotnet nuget push nuget/**/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
